Emoji Keyboard Functionality
KriteshTimsina/Wassupbroo-Chat-App pull request #3
Opened 2023-10-14 02:54 UTC by Namatuzio

Fixes #2 

Utilized Emoji-Mart (https://github.com/missive/emoji-mart) to implement an emoji picker into the message box area.

![Hacktoberfest_Emoji_Keyboard](https://github.com/KriteshTimsina/Wassupbroo-Chat-App/assets/55001591/c5c817d7-109b-4abd-bf02-1a6064ffe571)

If any updates for this PR are required please let me know!

2023-10-14 05:44 UTC, KriteshTimsina commented
Thank you for your contribution @Namatuzio . Your PR will be reviewed soon
.

2023-10-15 06:39 UTC, diwash007 requested changes
<img width="1435" alt="image" src="https://github.com/KriteshTimsina/Wassupbroo-Chat-App/assets/39879720/f460f455-3235-4b15-82b7-ee99db8188ab">
Emoji area is going down the page .. + it is covering the text

2023-10-15 08:08 UTC, Namatuzio commented
Hey @diwash007 so sorry for the implementation, I just pushed an update that should fix all the UI issues. 

I gave it a default size and a static position right above the message box. I also removed the emoji preview considering it was a little redundant. Thanks for looking everything over, and again please let me know if there are any other issues!

2023-10-15 08:59 UTC, diwash007 approved these changes
Looks good .. well done

2023-10-15 09:03 UTC, diwash007 commented
@Namatuzio Feel free to look out this project as well: https://github.com/diwash007/kurakani

2023-10-15 09:04 UTC, Namatuzio commented
Awesome, also would it be okay if the hacktoberfest-accepted label were to be added to this PR? Thanks again, and I'll definitely take a look!

2023-10-15 12:23 UTC, merged